fix: pointer references local var will cause random err
error report by gcc 13:
board/spacemit/k1-x/k1x.c: In function 'read_from_eeprom':
board/spacemit/k1-x/k1x.c:314:35: error: storing the address of local variable 'eeprom_data' in '*tlv_data' [-Werror=dangling-pointer=]
  314 |                         *tlv_data = tlv_entry;
      |                         ~~~~~~~~~~^~~~~~~~~~~
board/spacemit/k1-x/k1x.c:296:12: note: 'eeprom_data' declared here
  296 |         u8 eeprom_data[256];
      |            ^~~~~~~~~~~
board/spacemit/k1-x/k1x.c:294:44: note: 'tlv_data' declared here
  294 | void read_from_eeprom(struct tlvinfo_tlv **tlv_data, u8 tcode)
      |                       ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
cc1: all warnings being treated as errors

Change-Id: Id091b910bec31ba43e0368e50610eb5845a43869